name: Rachael Pereira Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aea594'
    - '#9a6263'
    - '#cecbc4'
    - '#600009'
  brandStrength: 0.5
  lightness: 0.8939683057833463
  saturation: 0.97809431492351
  rhythmicContrast: 0.34146146033890545
purpose: []
